### PR TITLE
Create main.py

### PR DESCRIPTION
**Pull request by trraney328**

### CODE REVIEW

**Comment by trraney328** [comment]
hey

**Comment by trraney328** [comment]
yeah, I'd wish the code would dang show

**Comment by darkdarcool** [comment]
yeh, i gtg to school, so I will look at them later. bai

**Comment by trraney328** [comment]
you ok?

**Comment by darkdarcool** [comment]
yeh

**Comment by trraney328** [comment]
hey

**Comment by darkdarcool** [comment]
hi, you dont need to comment, and keep making multiple pull requests, just work hard on one pull request's code, then make an actual pull request. I like to cut the git chat out.

**Comment by trraney328** [comment]
well, first before we make a pull request we need to have it in issue and then in pull request, thats what I did though

**Comment by darkdarcool** [comment]
ik, but make an example and cut the shit chat, and post them within a day of each other. This keeps everything organized.

**Pull request closed without merging**
